name: build

on:
  push:
env:
  PAWPAW_SKIP_LV2: 0
  PAWPAW_SKIP_GLIB: 0
  PAWPAW_SKIP_FLUIDSYNTH: 0

jobs:
  linux:
    strategy:
      matrix:
        target: [linux-x86_64]
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    permissions:
        contents: write
    steps:
      - name: Install git
        run: |
          apt-get update -qq && apt-get install -yqq --no-install-recommends ca-certificates curl git openssl
          curl -sLO https://launchpad.net/~kxstudio-debian/+archive/ubuntu/toolchain/+files/git_2.34.1-1ubuntu1~bpo20.04.1~ppa1_amd64.deb
          curl -sLO https://launchpad.net/~kxstudio-debian/+archive/ubuntu/toolchain/+files/git-man_2.34.1-1ubuntu1~bpo20.04.1~ppa1_all.deb
          dpkg -i *.deb
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: ${{ matrix.target }}
          pawpaw: true

  windows:
    strategy:
      matrix:
        target: [win64]
    runs-on: ubuntu-22.04
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: ${{ matrix.target }}
          pawpaw: true

  source:
    runs-on: ubuntu-20.04
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions
        with:
          target: source

#  pluginval:
#    runs-on: ubuntu-20.04
#    permissions:
#        contents: write
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          submodules: recursive
#      - uses: distrho/dpf-makefile-action@v1
#        with:
#          target: pluginval
#          pawpaw: true
